### ISSUE TITLE
Add 'statusKnown' to firebase-auth

### ISSUE THREAD

**Issue by newki** [firebase/polymerfire#23]
### Description
We need a way to know if authentication is still in progress.  For example, if we are using carbon-routing, we want to defer any routing events until we determine whether or not the user is authenticated (so we know to redirect them to login on the actual destination page).  If the user has previously been logged in, and returns to the page (page refresh), there is a delay before the persisted user object is loaded and set. We'd like to check this state before performing any routing.

### Expected Behavior
When true, login status can be determined by checking user property.

**Comment by Nipperstick** [comment]
Looking at the code, what is statusKnown an indication of?  If it suggests that you can’t rely on user alone to know whether a user is signed in (which is what the field comment suggests), then the implementation of _computeSignedIn (!!user) doesn’t follow that logic.

**Comment by fafcrumb** [comment]
You **can** rely on the user object to know if a user is signed in (when you have a user object). But you **can't** rely on it know if either a user is signed out, or if we just don't know either way yet. `_computeSignedIn` makes no distinction between those 2 states, and as far as I can tell it isn't really intended to. It returns true if you are definitely signed in, and false otherwise.
