### ISSUE TITLE
Add support for primitive elements in firebase-query

### ISSUE THREAD

**Issue by timoboz-priv** [firebase/polymerfire#25]
### Description
When iterating over primitive key/value pairs, firebase-query throws the following error:

```
FIREBASE WARNING: Exception was thrown by user callback. TypeError: Cannot create property '$key' on string 'own'
    at firebase-query.Polymer.__onFirebaseChildAdded
``` 

The "old" [firebase-collection](https://elements.polymer-project.org/elements/firebase-element?active=firebase-collection) handled this by wrapping primitive values in an object like this:

```
{
  value: /* original primitive value */
  __firebaseKey__: /* key of primitive value in parent document */
}
```

Please make the same functionality available in firebase-query.

### Steps to reproduce

Create a firebase-query element in a page and set path the "users" element, something like this:
```
users: {
  1: true,
  2: true,
  3: false
}
```

### Browsers Affected

- [x] Chrome
- [x] Firefox
- [x] Safari 9
- [x] Safari 8
- [x] Safari 7
- [x] Edge
- [x] IE 11
- [x] IE 10

**Comment by cdata** [comment]
Hi, thanks for reporting. `<firebase-query>` will not support queries for primitive children since it substantially complicates the implementation. The `<firebase-collection>` element from https://github.com/GoogleWebComponents/firebase-element was only able to achieve this behavior by [wrapping primitive values inside of objects](https://github.com/GoogleWebComponents/firebase-element/blob/master/firebase-collection.html#L493-L506). Please consider doing this yourself in your database to achieve the same effect. Please also refer to this issue: https://github.com/firebase/polymerfire/issues/6#issuecomment-220676842
