### ISSUE TITLE
signInWithPopup/signInWithRedirect methods never complete in IE 

### ISSUE THREAD

**Issue by rickymarcon** [firebase/polymerfire#48]
Attempts to authenticate via Google or Github using IE always hang and never complete. 

## Expected outcome
The popup dialog closes and the `user `property bound to `firebase-auth` gets populated. 

## Actual outcome
`firebase-auth` fires the following error message every time: "Error: The popup has been closed by the user before finalizing the operation."

## Steps to reproduce
- Trigger signInWithPopup('google')
- A popup with Google credentials shows
- Enter credentials
- It begins to authenticate

Outcome:
- The following close dialog appears:

<img src="https://cloud.githubusercontent.com/assets/778109/16029181/123ff6dc-322a-11e6-9106-6fddec2037d2.png" data-canonical-src="https://gyazo.com/eb5c5741b6a9a16c692170a41a49c858.png" width="300" />

- Shortly after, `firebase-auth` fires the following error message: "Error: The popup has been closed by the user before finalizing the operation." (Note: leaving the close dialog open results in the same response)

The problem occurs in both IE11 and IE10. 

I've also tried updating the `firebase-sdk` with the latest version to no avail. 

I'm not sure where the issue lies with this one...

**Comment by rickymarcon** [comment]
I resolved this issue for those who have yet to face this incredible pain...

You need to add your firebase auth domain url to IE's trusted sites:

Internet Options > Security > Select Trusted Sites Zone > Click on "Sites" > Add your firebase url (https://your-fb-name.firebaseapp.com

**Comment by DocSavage** [comment]
I've tried your suggested solution on Windows 7 / IE 10 and it still doesn't work :(

I also disabled an antivirus web plugin and even the pop-up blocker.  Still no go.  The pop-up says "Navigation to the webpage was canceled" and quickly disappears.  I occasionally get success using the FirebaseUI for web demo so will try that route:
https://github.com/firebase/firebaseui-web/tree/master/examples/demo

**Comment by gharibi** [comment]
I have added 'http://localhost:4200/' & 'https://<MyRepoName>.firebaseio.com' to the trusted websites.

I still have the issue with authentication. It gives me an error as below:
SCRIPT5022: Error: The popup has been closed by the user before finalizing the operation.

Also, below is the screenshot:
![2017-05-26_0-48-27](https://cloud.githubusercontent.com/assets/6460456/26473724/5dfee2fc-41ad-11e7-9106-3eb52113bd36.jpg)

FYI, I am using "firebase": "^4.0.0" & "@angular/core": "^4.0.0".

**Comment by brookesouza** [comment]
I was serving the site over SSL and hadn't added the root CA to the trusted root cert authority for the computer. Once the cert was validated, the error went away.

**Comment by hemakaraveenhansika** [comment]
Popup may be blocked by browser. Because of that, try to use redirect method. This worked for me.
More detail [https://firebase.google.com/docs/auth/web/google-signin](url)
`firebase.auth().signInWithRedirect(provider);`
And,
you can also retrieve the Google provider's OAuth token by calling getRedirectResult when your page loads.
`firebase.auth().getRedirectResult().then(function(result) {
  if (result.credential) {
    // This gives you a Google Access Token. You can use it to access the Google API.
    var token = result.credential.accessToken;
    // ...
  }
  // The signed-in user info.
  var user = result.user;
}).catch(function(error) {
  // Handle Errors here.
  var errorCode = error.code;
  var errorMessage = error.message;
  // The email of the user's account used.
  var email = error.email;
  // The firebase.auth.AuthCredential type that was used.
  var credential = error.credential;
  // ...
});`
