### ISSUE TITLE
Missing app-name attribute in firebase-document's docs

### ISSUE THREAD

**Issue by fernandezpaco** [firebase/polymerfire#70]
### Description
The docs is not indicating that app-name is necessary for firebase-document. I tried this code:

```html
<firebase-app id="app" name="enginevents" auth-domain="mydomain" database-url="myurl" api-key="mykey"></firebase-app>
<firebase-auth id="auth" app-name="enginevents" provider="google"></firebase-auth>
<firebase-document  id="doc" path="/eventlist" data="{{noteData}}"></firebase-document>
```
And the firebase-document was firing an exception because this.db was not initialized

So i changed the firebase-document line for this:
```html
<firebase-document  app-name="enginevents" id="doc" path="/eventlist" data="{{noteData}}"></firebase-document>
```

And now it works.

### Expected outcome

Docs should be accurate

### Actual outcome
Docs is missing that app-name is necessary

### Steps to reproduce

Try the code above

### Browsers Affected

- [ ] Chrome
- [ ] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by dmix007** [comment]
I'm able to get it to work with and without this "app-name" property.
Linux Mint 18
Polymer/polymer 1.6 (bower Polymer/polymer)
polymerfire 0.9.4 (bower info polymerfire)

**Comment by tjmonsi** [comment]
I think if you put an attribute `name` in the firebase-app, then you'll need to put an `app-name` in the firebase-document or firebase-query. This is because this will be the identification name for the firebase constructor being called globally.

If you didn't put any name, the name of the firebase-app is '[DEFAULT]', which will be used by the firebase-document or firebase-query.

You can try just calling firebase in your console by typing `console.log(firebase);` or something

**Comment by mbleigh** [comment]
Yep, I'd recommend omitting `name` from `firebase-app` unless you explicitly need to access multiple Firebase projects from a single site.
